### ISSUE TITLE
Using index for bam files.

### ISSUE THREAD

**Issue by griznog** [yzhernand/VNTRseek#9] opened 2019-02-24 00:36 UTC
Hi,

I'm trying to use an index with bam files, but when I add my index file in the FASTA directory, e.g.

```
$ ls
bam_14_sorted_griznog.bam  bam_14_sorted_griznog.bam.bai
```
However, this is picked up as two input files:

```
$ vntrseek 0 19 --dbsuffix ${DB_SUFFIX}
Could not read global config


Executing step #0 (creating MySQL database)...
Warning: Failed to create data directory!

Warning: Failed to create html directory!

Warning: Failed to create output directory!
done!


Executing step #1 (searching for tandem repeats in reads, producing profiles and sorting)...
2 supported files (bam format, assuming uncompressed) found in /tmp/7244420/fasta
Will use 4 processes
Processing bam chunk using: samtools view -F 256 -F 2048 -f 64 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chrM:1-16571
Processing bam chunk using: samtools view -F 256 -F 2048 -f 128 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chrM:1-16571
Processing bam chunk using: samtools view -F 256 -F 2048 -f 64 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chr1:1-249250621
Processing bam chunk using: samtools view -F 256 -F 2048 -f 128 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chr1:1-249250621
Running child, current_file = 1 (HASH(0x1e2e940))...
Running child, current_file = 0 (HASH(0x1e2ea18))...
Running child, current_file = 2 (HASH(0x1e2ebc8))...
Running child, current_file = 3 (HASH(0x1e0fc48))...
Processing bam chunk using: samtools view -F 256 -F 2048 -f 64 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chr2:1-243199373
Running child, current_file = 4 (HASH(0x1e2ea90))...
Processing bam chunk using: samtools view -F 256 -F 2048 -f 128 /tmp/7244420/fasta/bam_14_sorted_griznog.bam chr2:1-243199373
Running child, current_file = 5 (HASH(0x1ffd378))...
```

Is there a way to use the index file without duplicating each step? Our input files are pretty large and using an index really speeds things up.

**Comment by yzhernand** [comment] 2019-02-24 02:55
Hi,

This is actually behaving correctly, but the reported number of files found is incorrect. You're using 1.09.x?

The "duplicates" you are seeing are actually the result of VNTRseek reading each region/chromosome twice: once for each segment, because VNTRseek wants all reads in the set and it also needs each segment header to be labeled appropriately (eg, header/1, header/2). It's not reading duplicate data.

However, it is possible that the way we are reading BAM files is inefficient. I think that is partially because BAM files are not meant to be read by many concurrent processes, or at least not the way we are doing it.

If you know of a better way of processing BAM files, I would love your feedback. Our test data consisted primarily of FASTQ data. We ended up getting better performance just converting BAM files to FASTQ files with about 1 million reads per FASTQ file. Of course you have to make sure you extract only complete reads, and not any clipped/partial alignments to avoid the same read being represented multiple times. Also, segments from paired-end data need to be labeled (ie, the read header includes /1 or /2 at the end).

**Comment by griznog** [comment] 2019-02-24 16:05
I'm just the sysadmin so I'm checking with the person I'm setting this up for to see if we can switch to FASTQ and split the input file.  

We have a system with 360 cores and 10 TB (SGI UV300) that we'd like to scale this up on. 1.10.0-rc.2 seems to do well at splitting things up in my current test run.

```
slurm_script───perl───perl───48*[perl─┬─samtools]
                                      └─sh─┬─trf2proclu-ngs.]
                                           └─trf409-ngs.linu]
```

You'll be the first to know if we hit any snags ;)

**Comment by yzhernand** [comment] 2019-02-24 22:49
I've just made the 1.10.0-rc.3 tag after accepting your pull request and adding my latest update. I think you should try this one. It splits up BAM files by smaller regions than just by chromosomes, which should play nice on clusters that abort long-running processes.

Again, if you're able to use FASTQ that might be better until we find out what we might be able to do to optimize BAM.

**Comment by yzhernand** [comment] 2019-03-07 23:28
Closing as this is not a bug, and the 1.09.x branch is going to be deprecated.

**Closed as completed by yzhernand** 2019-03-07 23:28 UTC
